sudo: false

language: php

branches:
  except:
    - /^release-\d+\.\d+\.\d+.*$/
    - /^ghgfk-.*$/

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.local
    - zf-mkdoc-theme

env:
  global:
    - SITE_URL: https://zendframework.github.io/zend-debug
    - GH_USER_NAME: "Matthew Weier O'Phinney"
    - GH_USER_EMAIL: matthew@weierophinney.net
    - GH_REF: github.com/zendframework/zend-debug.git
    - secure: "L2VCLoMn2dvOci7YvfIPOx8a3DikGtCj8NuQve5IoE2LMCMyDwO78vgQ+/phcz8k+Acw9XBthtlIIJvjhtlN1rgywAhoEEO/QmtqIUmzPwFTEgP8un0L6I9K4rZMEJ0akKrEVDGyZzXFv3xCXyANzqIo7aVAoFFbnGjKo/Dktb1RBFkiAitVLcNAcNud/JxTvscsI4Y7Cx/sCmG6AgYm+4ibGo8Ev+L3etK+00IovTALxhKmu53PIIxUxClmMOTQ4wny6H6JNwcm9xr83Mxhn0jUWQeVlFXUEUGKC9IxHGaCa5pBOv2vtRyWrUkMzzqiZjtAGaRNCIiPx3PmXJmE1Z1sEQ3NuCbx8JBnF9pRg2Ewloc8nqRnTXzciJOsFgrifWEQBgajv12+WsWmpkrofYZ3HLdyWd7a5UT5T3xqtM3YnMKQe4j3uM43k+crlEFsxwUcf8i3Kcbm4PvkP0RPdyOgwdNAd6oMrzu2vQL6qwunuFipLkj475z8psSAuo3fPzI9FygaLf3pJMeRHPiv3yKotnAvge4JhBAPC90SvY/irjgB+hDitRemLHfKvdC6U2eC0uAhFCpI3kiv9oS8QRwdx+yzGXW1tRUbbMiye582QRgRZaJPKYw9w6NciGPAMsxGfoo+nNK9Lqx7XbI6KNZFwcLRmpVH7zpjiYL7Tto="

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env:
        - EXECUTE_CS_CHECK=true
    - php: 5.6
      env:
        - EXECUTE_TEST_COVERALLS=true
        - DEPLOY_DOCS="$(if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then echo -n 'true' ; else echo -n 'false' ; fi)"
        - PATH="$HOME/.local/bin:$PATH"
    - php: 7
    - php: hhvm 
  allow_failures:
    - php: hhvm

notifications:
  irc: "irc.freenode.org#zftalk.dev"
  email: false

before_install:
  - if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - composer self-update
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then travis_retry php vendor/bin/php-coveralls -v ; fi

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs

script:
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then ./vendor/bin/phpunit --coverage-clover clover.xml ; fi
  - if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then ./vendor/bin/phpunit ; fi
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then ./vendor/bin/php-cs-fixer fix -v --diff --dry-run ; fi
  - if [[ $DEPLOY_DOCS == "true" && "$TRAVIS_TEST_RESULT" == "0" ]]; then wget -O theme-installer.sh "https://raw.githubusercontent.com/zendframework/zf-mkdoc-theme/master/theme-installer.sh" ; chmod 755 theme-installer.sh ; ./theme-installer.sh ; fi

after_success:
  - if [[ $DEPLOY_DOCS == "true" ]]; then echo "Preparing to build and deploy documentation" ; ./zf-mkdoc-theme/deploy.sh ; echo "Completed deploying documentation" ; fi

after_script:
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then travis_retry php vendor/bin/php-coveralls -v ; fi
